# Generated by Django 5.0.6 on 2025-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_position", models.IntegerField(default=0)),
                ("y_position", models.IntegerField(default=0)),
                ("is_processing", models.BooleanField(default=False)),
                ("is_moving", models.BooleanField(default=False)),
                ("command_queue", models.JSONField(default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
