# Generated by Django 5.0.6 on 2025-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_position", models.IntegerField()),
                ("y_position", models.IntegerField()),
                ("status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="machinestate",
            name="command_queue",
        ),
        migrations.RemoveField(
            model_name="machinestate",
            name="is_moving",
        ),
        migrations.RemoveField(
            model_name="machinestate",
            name="is_processing",
        ),
        migrations.AddField(
            model_name="machinestate",
            name="status",
            field=models.CharField(default="idle", max_length=10),
        ),
    ]
